// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package signaling

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[RoomCreated-1]
	_ = x[GuestAuth-2]
	_ = x[GuestJoined-3]
	_ = x[HostAuth-4]
	_ = x[IceCandidate-5]
	_ = x[GuestDisconnected-6]
	_ = x[KickGuest-7]
}

const _MsgType_name = "InvalidRoomCreatedGuestAuthGuestJoinedHostAuthIceCandidateGuestDisconnectedKickGuest"

var _MsgType_index = [...]uint8{0, 7, 18, 27, 38, 46, 58, 75, 84}

func (i MsgType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MsgType_index)-1 {
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[idx]:_MsgType_index[idx+1]]
}
